model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_loss'
  dirpath: "ckpts"
  filename: "mnist-{epoch:02d}-{val_loss:.2f}"
  #every_n_train_steps: 10000
  save_top_k: 1
  save_last: True
  mode: 'min'
