model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_loss' 
  dirpath: "checkpoints"
  filename: "ckpt-{epoch:02d}-{val_loss:.2f}"
  every_n_train_steps: null 
  save_top_k: 3  
  save_last: True 
  mode: 'min'  
